# Generated by Django 4.1.3 on 2022-12-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogALYH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
    ]
